export * from './header'
export * from './hero'
export * from './skills'
export * from './works'
export * from './works2'
export * from './education'
export * from './contacts'
export * from './footer'